- name: Demo on loop
  hosts: all
  tasks:
    - name: Print fruitnames
      debug:
        msg: "Fruit = {{ item }}"
      loop:
        - banana
        - apple
        - orange

    - name: Create servers
      debug:
        msg: "{{ item.name }}"
      loop:
        - name: server1
          disks: 3gb
          ram: 15Gb
          network:
            nic01: 100Gb
            nic02: 10Gb
        - name: server2
          disks: 3gb
          ram: 15Gb
          network:
            nic01: 100Gb
            nic02: 10Gb
      loop_control:
        label: "{{ item.name }}"

    - name: Count our fruit
      debug:
        msg: "{{ item }} with index {{ my_idx }}"
      loop:
        - apple
        - banana
        - pear
      loop_control:
        index_var: my_idx

    - name: Loop variable
      debug:
        msg: "{{ myvar }}"
      loop:
        - apple
        - banana
        - pear
      loop_control:
        loop_var: myvar


    - name: print first value
      #when: ansible_loop.first
      debug:
        msg: "{{ ansible_loop.first }}"
      loop:
        - apple
        - banana
        - pear
      loop_control:
        extended: yes
